import { request } from '../api/apiClient'; import type { CheckIn, Event, EventStatus, Registration, Ticket, User } from '../types'
type ApiEvent={id:string;organizer_id:string;title:string;description:string;location:string;start_time:string;end_time:string;capacity:number;registered_count:number;status:EventStatus;category:string;banner_image:string;created_at:string}
const event=(e:ApiEvent):Event=>({id:e.id,organizerId:e.organizer_id,title:e.title,description:e.description,location:e.location,startTime:e.start_time,endTime:e.end_time,capacity:e.capacity,registeredCount:e.registered_count,status:e.status,category:e.category,bannerImage:e.banner_image,createdAt:e.created_at})
const payload=(v:Omit<Event,'id'|'registeredCount'|'status'|'createdAt'|'organizerId'>)=>({title:v.title,description:v.description,location:v.location,start_time:v.startTime,end_time:v.endTime,capacity:v.capacity,category:v.category,banner_image:v.bannerImage})
export const eventService={getEvents:async()=> (await request<ApiEvent[]>('/events')).map(event),getEvent:async(id:string)=>event(await request<ApiEvent>(`/events/${id}`)),create:async(input:Omit<Event,'id'|'registeredCount'|'status'|'createdAt'|'organizerId'>,_u:User)=>event(await request<ApiEvent>('/events',{method:'POST',body:JSON.stringify(payload(input))})),transition:async(id:string,s:EventStatus)=>event(await request<ApiEvent>(`/events/${id}/transition`,{method:'POST',body:JSON.stringify({status:s})}))}
export const registrationService={mine:(_id:string)=>request<Registration[]>('/registrations/me'),get:(id:string)=>request<Registration>(`/registrations/${id}`),register:(eventId:string,_u:User)=>request<{registration:Registration;ticket:Ticket}>(`/events/${eventId}/register`,{method:'POST'}),cancel:(id:string)=>request<Registration>(`/registrations/${id}/cancel`,{method:'POST'})}
export const ticketService={get:(id:string)=>request<Ticket>(`/tickets/${id}`),forRegistration:(id:string)=>request<Ticket>(`/registrations/${id}/ticket`)}
export const checkinService={checkin:(code:string,_u:User)=>request<CheckIn>('/checkins',{method:'POST',body:JSON.stringify({ticket_code:code})})}
export const organizerService={dashboard:async()=>{const data=await request<{events:ApiEvent[];total_registrations:number;total_checkins:number}>('/organizer/dashboard');return {...data,events:data.events.map(event)}}}
