from datetime import datetime
from uuid import uuid4
from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from .db import Base
def uid(): return str(uuid4())
class User(Base):
    __tablename__='users'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name:Mapped[str]=mapped_column(String(120)); email:Mapped[str]=mapped_column(String(254),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); role:Mapped[str]=mapped_column(String(16),index=True); avatar_url:Mapped[str]=mapped_column(String(500),default=''); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow)
class Event(Base):
    __tablename__='events'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); organizer_id:Mapped[str]=mapped_column(ForeignKey('users.id'),index=True); title:Mapped[str]=mapped_column(String(200)); description:Mapped[str]=mapped_column(Text); location:Mapped[str]=mapped_column(String(300)); start_time:Mapped[datetime]=mapped_column(DateTime); end_time:Mapped[datetime]=mapped_column(DateTime); capacity:Mapped[int]=mapped_column(Integer); registered_count:Mapped[int]=mapped_column(Integer,default=0); status:Mapped[str]=mapped_column(String(16),default='DRAFT',index=True); category:Mapped[str]=mapped_column(String(80)); banner_url:Mapped[str]=mapped_column(String(500)); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class StaffEventAssignment(Base):
    __tablename__='staff_event_assignments'; __table_args__=(UniqueConstraint('staff_id','event_id',name='uq_staff_event'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); staff_id:Mapped[str]=mapped_column(ForeignKey('users.id'),index=True); event_id:Mapped[str]=mapped_column(ForeignKey('events.id'),index=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Registration(Base):
    __tablename__='registrations'; __table_args__=(UniqueConstraint('event_id','attendee_id',name='uq_event_attendee'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); event_id:Mapped[str]=mapped_column(ForeignKey('events.id'),index=True); attendee_id:Mapped[str]=mapped_column(ForeignKey('users.id'),index=True); registered_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); status:Mapped[str]=mapped_column(String(16),default='REGISTERED')
class Ticket(Base):
    __tablename__='tickets'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); registration_id:Mapped[str]=mapped_column(ForeignKey('registrations.id'),unique=True,index=True); ticket_code:Mapped[str]=mapped_column(String(32),unique=True,index=True); qr_value:Mapped[str]=mapped_column(String(255)); status:Mapped[str]=mapped_column(String(16),default='VALID'); issued_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Checkin(Base):
    __tablename__='checkins'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); ticket_id:Mapped[str]=mapped_column(ForeignKey('tickets.id'),unique=True,index=True); event_id:Mapped[str]=mapped_column(ForeignKey('events.id'),index=True); attendee_id:Mapped[str]=mapped_column(ForeignKey('users.id'),index=True); checked_in_by:Mapped[str]=mapped_column(ForeignKey('users.id')); checked_in_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); status:Mapped[str]=mapped_column(String(16),default='SUCCESS')
class RefreshToken(Base):
    __tablename__='refresh_tokens'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); user_id:Mapped[str]=mapped_column(ForeignKey('users.id'),index=True); token_hash:Mapped[str]=mapped_column(String(64),unique=True); expires_at:Mapped[datetime]=mapped_column(DateTime); revoked_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
