/** English product copy. Backend error codes never reach the interface verbatim. */
export const errors = {
  INVALID_CREDENTIALS: 'Email or password is incorrect.',
  EMAIL_TAKEN: 'This email already has an account. Sign in instead.',
  UNAUTHORIZED: 'Your session ended. Sign in again.',
  FORBIDDEN: "You don't have access to this.",
  EVENT_NOT_FOUND: "We couldn't find that event.",
  TICKET_NOT_FOUND: "We couldn't find that ticket.",
  REGISTRATION_NOT_FOUND: "We couldn't find that registration.",
  REGISTRATION_CLOSED: "Registration isn't open for this event.",
  EVENT_STARTED: 'This event has already started, so registration is closed.',
  ALREADY_REGISTERED: "You've already registered for this event.",
  EVENT_FULL: 'This event is full.',
  INVALID_TICKET: 'No ticket matches this code. Check it and try again.',
  TICKET_CANCELLED: 'This ticket was cancelled.',
  TICKET_ALREADY_USED: 'This ticket was already scanned.',
  CHECKIN_CLOSED: 'Check-in is closed. Check-in works only while check-in is open.',
  WRONG_EVENT: 'This ticket belongs to another event. Select the correct event.',
  CANCELLATION_CLOSED: 'Cancellation is only available while registration is open.',
  CAPACITY_TOO_SMALL: 'Capacity cannot be lower than the number of registrations.',
  EVENT_NOT_EDITABLE: 'This event can no longer be edited.',
  NOTIFICATION_FAILED: 'The notification service is unavailable. Try again.',
  INVALID_EVENT_TIME: 'The start time must be in the future and before the end time.',
  EVENT_NOT_DELETABLE: 'Only drafts can be deleted.',
  INVALID_TRANSITION: "This event can't move to that step from where it is now.",
  INVALID_STAFF: 'Choose a staff account.',
  ALREADY_ASSIGNED: 'This person is already assigned.',
  VALIDATION_ERROR: 'Check the highlighted fields and try again.',
  CURSOR_NOT_FOUND: 'The event list changed. Refresh the list to continue.',
  network: "We couldn't connect. Check your connection and try again.",
  server: 'The service is unavailable. Try again in a moment.',
  fallback: "We couldn't complete that action. Try again.",
} as const;


/* Nội dung web MVP tập trung để sửa thông báo đồng nhất giữa các màn hình. */
export const strings = {
  appName: 'Evently',
  brandMark: 'e',
  status: {
    DRAFT: { label: 'Draft', hint: 'Publish this draft to open registration.' },
    PUBLISHED: { label: 'Published', hint: 'Public. Registration closes when check-in opens or the start time passes.' },
    ONGOING: { label: 'Preparing', hint: 'Registration closed. Check-in has not opened yet.' },
    STARTED: { label: 'Check-in open', hint: 'Staff and organizer can check in until the end time.' },
    COMPLETED: { label: 'Ended', hint: 'The event has completed. Check-in and registration are closed.' },
    CANCELLED: { label: 'Cancelled', hint: 'The event was cancelled. Check-in and registration are closed.' },
  },
  nav: {
    overview: 'Overview',
    myTickets: 'My tickets',
    door: 'Check-in',
    newEvent: 'Create event',
    skip: 'Skip to content',
    home: 'Evently home',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    primary: 'Primary',
    signOut: 'Sign out',
    signedOut: 'Signed out.',
    explore: 'Explore',
    myRegistrations: 'My registrations',
    checkin: 'Check-in',
    dashboard: 'Dashboard',
    live: 'Dashboard',
    events: 'Events',
    createEvent: 'Create event',
  },
  auth: {
    welcomeBack: 'WELCOME BACK',
    signInTitle: 'Sign in',
    joinTitle: 'Create an account',
    slogan: 'Find an event.',
    secondLine: 'Walk in with a QR code.',
    logo: 'Evently',
    signupBody: 'Register for events and keep your tickets in one place.',
    nameRequired: 'Enter your name.',
    nameLong: 'Use 120 characters or fewer.',
    passwordLong: 'Use 128 characters or fewer.',
    emailInvalid: 'Enter a valid email address.',
    loginIdentifier: 'Email or demo username',
    loginInvalid: 'Enter an email or a demo username such as staff1.',
    passwordShort: 'Use at least 6 characters.',
    passwordRequired: 'Enter your password.',
    passwordMismatch: 'Passwords do not match.',
    passwordHint: 'At least 6 characters.',
    created: 'Account created.',
    demoRoles: { attendee: 'Attendee', staff: 'Staff', organizer: 'Organizer' },
    demoAccounts: { attendee: 'user1–user100 (1–100)', staff: 'staff1–staff5 (1–5)', organizer: 'organizer1–organizer2 (1–2)', password: '123456' },
    name: 'Name',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    signIn: 'Sign in',
    signUp: 'Sign up',
    newHere: 'New here?',
    createAccount: 'Create an account',
    backToSignIn: 'Back to sign in',
    signupNote: 'Already have an account?',
    sessionExpired: 'Session expired. Please sign in again.',
    signedOut: 'Signed out.',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
  },
  common: {
    loading: 'Loading…',
    retry: 'Try again',
    cancel: 'Cancel',
    close: 'Close',
    save: 'Save',
    send: 'Send',
    confirm: 'Confirm',
    back: 'Back',
    search: 'Search',
    imageUrlPlaceholder: 'https://',
    thisEvent: 'this event',
    noResults: 'No events match your filters',
    clearFilters: 'Clear filters',
    manage: 'Manage',
    viewTicket: 'View ticket',
    copy: 'Copy',
    copied: 'Copied',
    copiedCode: 'Ticket code copied.',
    goHome: 'Go to my home',
    goBack: 'Go back',
    offline: "You're offline. Changes will work again when you reconnect.",
    loadingPage: 'Loading page',
    qrLabel: (value: string) => `Ticket QR code ${value}`,
    trend: (first: number, last: number) => `Registrations trend from ${first} to ${last}`,
  },
  ticket: {
    valid: 'Valid',
    used: 'Checked in',
    cancelled: 'Cancelled',
    copyCode: 'Copy code',
    manualCopy: 'Select the code and copy it manually.',
    back: 'Back to my tickets',
    instruction: 'Show this at check-in. Brightness up helps scanners.',
    usedInstruction: 'You have already checked in with this ticket.',
    cancelledInstruction: 'This ticket cannot be used at check-in.',
    label: (state: string, title: string) => `${state} ticket for ${title}`,
    timeRange: (start: string, end: string) => `${start} to ${end}`,
  },
  clock: {
    justNow: 'just now',
    secondsAgo: (count: number) => `${count}s ago`,
    minutesAgo: (count: number) => `${count} min ago`,
    hoursAgo: (count: number) => `${count} hour${count > 1 ? 's' : ''} ago`,
    daysAgo: (count: number) => `${count} day${count > 1 ? 's' : ''} ago`,
    startsIn: (time: string) => `Starts in ${time}`,
    endsIn: (time: string) => `Ends in ${time}`,
  },
  explore: {
    title: 'Explore',
    search: 'Search events',
    open: 'Open for registration',
    happening: 'Preparing / check-in open',
    past: 'Past',
    soonest: 'Soonest',
    sortSoonest: 'Sort: Soonest',
    latest: 'Latest first',
    sort: 'Sort events',
    loadMore: 'Load more',
    empty: 'No events match.',
    emptyBody: 'Clear the search to see everything.',
    clearSearch: 'Clear search',
    nextTicket: 'Your next event',
    left: (remaining: number, capacity: number) => `${remaining} of ${capacity} left`,
    low: (remaining: number) => `${remaining} left`,
    closed: 'Registration closed',
    doorOpen: 'Check-in open now',
    checkedIn: 'Checked in',
    refreshing: 'Updating events…',
    happeningNow: 'Happening now — your tickets',
    forYou: 'For you',
    browseAll: 'Browse all events',
    going: 'going',
    spotsLeft: 'spots left',
    soldOut: 'Sold out',
    almostFull: 'Almost full',
  },
  detail: {
    back: 'Explore',
    register: 'Register',
    signInToRegister: 'Sign in to register',
    going: "You're registered",
    registeredMark: '✓ Registered',
    organizerView: "You're viewing this as an organizer.",
    staffView: "You're viewing this as staff. Registration is for attendee accounts.",
    previouslyCancelled: "You cancelled your registration and can't register again for this event.",
    attendeeOnly: 'Sign in with an attendee account to register.',
    manageEvent: 'Manage event',
    confirmTitle: 'Confirm registration',
    confirmBody: (title: string) => `Register for ${title}? Your ticket is created right away.`,
    actionRegion: 'Registration action',
    soldOut: 'Sold out',
    eventEnded: 'This event has ended.',
    cancelledBanner: 'This event was cancelled.',
    justSoldOut: 'This event just sold out',
    registeredToast: "You're registered",
    about: 'About this event',
    details: 'Details',
    organizedBy: 'Organized by',
  },
  registrations: {
    title: 'My tickets',
    tabs: { upcoming: 'Upcoming', past: 'Past', cancelled: 'Cancelled' },
    empty: 'No tickets here yet.',
    emptyBody: 'Find an event and register to get your first ticket.',
    cancellationLocked: 'Cancellation closed',
    cancellationWarning: (title: string) => `Cancel your ticket for ${title}? Your spot goes back to the pool and you can't register again.`,
    cancelledEvent: 'This event was cancelled.',
    cancelledTicket: 'Cancelled',
    cancelTitle: 'Cancel registration',
    cancelToast: 'Registration cancelled. Your spot was released.',
    checkedInAt: 'Checked in at',
    notCheckedIn: 'Not checked in yet',
    startsIn: 'Starts in',
  },
  staff: {
    you: 'You',
    title: 'Check-in',
    picker: 'Event',
    assignedEvents: 'Assigned events',
    noEventsBody: "You aren't assigned to any events yet. Ask the organizer to add you.",
    closedBefore: "Check-in hasn't opened. The organizer can open check-in, or it opens automatically 15 minutes before the start time.",
    closedAfter: 'This event has ended. Check-in is closed.',
    closedCancelled: 'This event was cancelled. Check-in is closed.',
    closedPreparation: 'Registration is closed while the organizer prepares the event. Check-in has not opened yet.',
    doorOpen: 'Check-in open',
    scan: 'Scan',
    scanHint: 'Type or scan a ticket code, then press Enter.',
    session: 'This session',
    sessionHint: 'Only scans made on this page. These are not all check-ins for the event.',
    sessionEmpty: 'Scan a ticket to start this session.',
    serverHistory: 'Recent check-ins',
    serverHistoryHint: 'Latest 100 check-ins recorded for this event, including other check-in staff.',
    admitted: 'Admitted',
    used: 'Already scanned',
    notFound: 'Not found',
    cancelled: 'Ticket cancelled',
    closed: 'Check-in closed',
    forbidden: 'Access denied',
    failed: 'Could not scan',
    admittedOther: (title: string) => `Admitted to ${title}`,
    anotherEvent: 'another assigned event',
    wrongSelection: 'The ticket belongs to another event you can check in. Select that event to see its check-ins.',
    registered: 'Registered',
    checkedInCount: 'Checked in',
    lastScan: 'Last scan',
    of: 'of',
    recentCount: (count: number) => `${count} recent check-ins`,
    scanCode: 'Code',
    scanResult: 'Result',
    scanTime: 'Time',
    subtitle: 'Select an event, enter a ticket code, and watch entries arrive live.',
    noEvents: 'No events assigned to you yet.',
    scanTitle: 'Scan ticket',
    checkinOpenIn: 'Check-in opens in',
    notOpenYet: 'Check-in is not open yet',
    eventEnded: 'This event has ended. Check-in is closed.',
    codeLabel: 'Ticket code',
    codePlaceholder: 'EV-XXXXXXXX',
    validate: 'Validate & check in',
    checking: 'Checking…',
    success: 'checked in',
    alreadyUsed: 'Already checked in at',
    invalidCode: 'Invalid ticket code',
    wrongEvent: 'Ticket belongs to another event',
    notOpen: 'Check-in is not open',
    historyTitle: 'Checked-in tickets',
    historySearch: 'Search name or code',
    historyEmpty: 'No check-ins yet.',
    ofRegistered: 'of registered',
    sound: 'Beep on success',
  },
  organizer: {
    previousPage: 'Previous',
    nextPage: 'Next',
    pageNumber: (page: number) => `Page ${page}`,
    nothingScheduled: 'Nothing scheduled. Create an event to get started.',
    form: {
      basics: 'Basics',
      whenWhere: 'When and where',
      banner: 'Banner',
      title: 'Title',
      description: 'Description',
      category: 'Category',
      start: 'Start',
      end: 'End',
      location: 'Location',
      capacity: 'Capacity',
      imageUrl: 'Image URL',
      bannerPreview: 'Banner preview',
      imageError: "Can't load this image.",
      imageEmpty: 'Add an image URL to preview your banner.',
      preview: 'Event preview',
      previewTitle: 'Your event title',
      previewLocation: 'Your event location',
      previewTime: 'Choose a valid start time.',
      create: 'Create draft',
      created: 'Draft created.',
      titleRequired: 'Enter an event title.',
      titleLong: 'Use 200 characters or fewer.',
      descriptionRequired: 'Add a description.',
      locationRequired: 'Enter a location.',
      capacityInvalid: 'Use a whole number of at least 1.',
      startRequired: 'Choose a valid start time.',
      endRequired: 'Choose a valid end time.',
      startFuture: 'The start time must be in the future.',
      endAfter: 'The end time must be after the start time.',
      bannerInvalid: 'Use an http or https image URL.',
      duration: (hours: number, minutes: number) => `${hours}h ${String(minutes).padStart(2, '0')}m`,
      durationLabel: (duration: string) => `Duration: ${duration}`,
      categories: ['Technology', 'Business', 'Design', 'Career', 'Community', 'Education', 'Other'],
    },
    overview: 'Overview',
    eventsTitle: 'Events',
    newEvent: 'Create event',
    registered: 'Registered',
    checkedIn: 'Checked in',
    eventCount: (count: number) => `${count} ${count === 1 ? 'event' : 'events'}`,
    publishedCount: (count: number) => `${count} published`,
    next: (title: string, reason: string) => `Next: ${title}. ${reason}`,
    noAttention: 'Everything is on track.',
    nextEvents: 'Next events',
    empty: 'No events yet',
    emptyBody: 'Create your first draft to get started.',
    search: 'Search title, category or location',
    filter: 'Filter by status',
    allStatuses: 'All statuses',
    statusAll: 'Status: All',
    statusOption: (label: string) => `Status: ${label}`,
    sortOption: (label: string) => `Sort: ${label}`,
    currentEvent: (title: string) => `Now: ${title}. Check-in is open.`,
    nextEvent: (title: string, countdown: string) => `Next: ${title} starts in ${countdown}.`,
    draftEvent: (title: string) => `${title} is a draft. Publish it to open registration.`,
    sort: 'Sort events',
    soonest: 'Soonest',
    mostRegistered: 'Most registered',
    attentionReasons: {
      draft: 'Draft waiting to be published',
      preparing: 'Preparing; check-in has not opened',
      started: 'Check-in open',
      overdue: 'Past the scheduled start; check status',
      soon: 'Starts within an hour',
      full: 'Sold out',
      nearlyFull: 'At least 90% registered',
      noStaff: 'Upcoming event has no assigned staff',
    },
    overviewEyebrow: 'ORGANIZER OVERVIEW',
    totalEvents: 'Total events',
    published: 'Published',
    registrations: 'Registrations',
    checkins: 'Check-ins',
    needsAttention: 'Needs attention',
    recentEvents: 'Recent events',
    allEvents: 'All events',
    manageEyebrow: 'EVENT MANAGEMENT',
    yourEvents: 'Your events.',
    manageHint: 'Search, filter and open any event to manage its lifecycle.',
    createEyebrow: 'NEW EVENT',
    createTitle: 'Create an event',
    createDraft: 'Create draft event',
    autoNote:
      'Check-in opens automatically 15 minutes before the start time and closes when the event ends.',
    liveEyebrow: 'REALTIME',
    activityTitle: 'Recent activity',
    updatedAt: 'Updated at',
    endedFinal: 'Ended: data is final',
  },
  manage: {
    affectedCount: (count: number) => `${count} registered attendees are affected.`,
    facts: { when: 'When', where: 'Where', category: 'Category', capacity: 'Capacity', door: 'Check-in status' },
    staff: 'Staff',
    schedule: 'Schedule',
    door: 'Check-in',
    backEvents: '← Events',
    publicPage: 'View public page',
    lifecycleLabel: 'Event lifecycle',
    cancelledBanner: 'This event was cancelled.',
    lockedSchedule: 'The schedule is locked once event preparation has started.',
    scheduleWarning: (count: number) => `${count} people are registered. They will see the new schedule; use Notify attendees to tell them about the change.`,
    savedSchedule: 'Schedule saved.',
    prepare: 'Begin preparation',
    startEvent: 'Start event',
    completeEvent: 'Complete event',
    noActions: 'This event has finished. No lifecycle actions are available.',
    prepareBody: 'Registration will close. Check-in stays closed until you start the event.',
    startBody: 'Registration will close and staff can check in tickets immediately.',
    completeBody: 'Check-in will close and this event will become read-only. The server will send the completion notification.',
    publishBody: 'This draft becomes public and registration opens until check-in starts.',
    cancelBody: (count: number) => `Cancelling stops registration and check-in for the ${count} people who signed up. This cannot be undone. The server will send the cancellation notification.`,
    deleteBody: 'This draft will be permanently deleted. This cannot be undone.',
    notifyBody: (count: number, title: string) => `Send a notification to the ${count} people registered for ${title}?`,
    notified: (count: number) => `Notified ${count} attendees.`,
    simulatedNotify: (count: number) => `Notification simulated for ${count} attendees.`,
    publishedToast: 'Published.',
    preparedToast: 'Preparation started.',
    startedToast: 'Event started.',
    completedToast: 'Event completed.',
    cancelledToast: 'Event cancelled.',
    deletedToast: 'Draft deleted.',
    chooseStaff: 'Choose a staff account',
    assign: 'Assign',
    noStaff: 'No staff assigned yet. Add someone so they can check people in.',
    noAvailableStaff: 'All available staff accounts are assigned to this event.',
    assignedToast: 'Staff assigned.',
    createStaff: 'New staff account',
    createStaffButton: 'Create staff account',
    staffCreated: 'Staff account created. Select it below to assign it to this event.',
    staffCreatedAssigned: 'Staff account created and assigned.',
    staffAssignFailed: 'The staff account was created, but assignment failed. Select the account and try Assign again.',
    registeredCount: (count: number, capacity: number) => `Registered ${count} of ${capacity}`,
    overview: 'Overview',
    checkin: 'Check-in',
    settings: 'Settings',
    lifecycle: 'Lifecycle actions',
    publish: 'Publish',
    openCheckin: 'Open check-in now',
    complete: 'Mark completed',
    cancelEvent: 'Cancel event',
    deleteDraft: 'Delete draft',
    notify: 'Notify attendees',
    send: 'Send',
    howItWorks: 'How it works',
    howItWorksItems: [
      'Check-in opens automatically 15 minutes before start.',
      'It closes and the event completes when the end time passes.',
      'PUBLISHED: attendees can register.',
      'ONGOING: organizer only. STARTED: staff and organizer can check in.',
    ],
    notifyTitle: 'Notify attendees',
    notifyWillSend: 'Will be sent to {n} registered attendees.',
    notifySent: 'Notification sent to {n} attendees.',
    cancelConfirmTitle: 'Cancel this event?',
    cancelConfirmBody:
      'Cancelling will notify {n} registered attendees and cannot be undone.',
    cancelConfirmCheck: 'I understand this cannot be undone',
    cancelCta: 'Yes, cancel event',
    rescheduleNote: '{n} attendees are registered; they will see the new time.',
    saveSchedule: 'Save schedule',
    assignStaff: 'Assign staff',
    newStaff: '+ New staff account',
    createAndAssign: 'Create & assign',
    assigned: 'Assigned staff',
    dangerZone: 'Danger zone',
    viewPublic: 'View public page',
    checkinOpenUntil: 'Check-in is open until {t}',
    checkinDirectNote: 'Organizers can check in tickets directly for this event.',
  },
  live: {
    title: 'Dashboard',
    subtitle: 'Registrations and places remaining, as they change.',
    event: 'Event',
    manage: 'Manage event',
    registered: 'registered',
    ofCapacity: (capacity: number) => `of ${capacity}`,
    left: (remaining: number) => `${remaining} left`,
    changes: 'Last changes (this session)',
    changesEmpty: 'Waiting for the next registration.',
    final: (status: string) => `This event is ${status.toLowerCase()}. Numbers are final.`,
    draft: 'This is a draft. Publish it to open registration.',
    updated: 'Updated',
    snapshotWaiting: 'Waiting for the first update…',
    noEvents: 'No events yet',
    noEventsBody: 'Create an event to watch registrations here.',
    delta: (count: number) => `${count > 0 ? '+' : ''}${count}`,
    deltaBody: (count: number) => `${Math.abs(count)} ${Math.abs(count) === 1 ? 'registration' : 'registrations'} ${count > 0 ? 'added' : 'cancelled'}`,
    connection: { open: 'Live', connecting: 'Connecting…', reconnecting: 'Reconnecting…', paused: 'Paused', polling: 'Updating by polling' },
    groups: { live: 'Live now', upcoming: 'Upcoming', past: 'Past' },
    full: 'FULL',
    newRegistration: 'A new registration',
    registrationCancelled: 'A registration was cancelled',
    updatedAt: 'Updated at',
    endedFinal: 'Ended: data is final',
  },
  errors: {
    forbiddenTitle: "You don't have access to this page.",
    notFoundTitle: "That page doesn't exist.",
    wentWrong: 'Something went wrong. Please try again.',
    loadFailed: 'Failed to load. Please try again.',
  },
} as const;
